resources:
  - name: repository
    type: git
    source:
      uri: https://((github-token))@github.com/cirocosta/buildkit-task

  - name: image
    type: registry-image
    source:
      repository: cirocosta/buildkit-task

  - name: buildkit-master-image
    type: registry-image
    source:
      repository: moby/buildkit
      tag: master-rootless


jobs:
  - name: build
    plan:
      - in_parallel:
          steps:
            - get: repository
              trigger: true
            - get: image
            - get: buildkit-master-image
              trigger: true
      - task: build
        file: repository/task.yml
        image: image
        input_mapping: {context: repository}
        privileged: true
